-- Product 
CREATE TABLE "HBN_PRODUCT" 
( "ID" NUMBER(9,0) NOT NULL, 
  "NAME" VARCHAR2(100 BYTE) NOT NULL,
  "STATE" VARCHAR2(50 BYTE) NOT NULL,
  "AMOUNT" NUMBER(7,2) NOT NULL, 
  
  CONSTRAINT "PK_HBN_PRODUCT" PRIMARY KEY ("ID")
);

-- Forecast 
CREATE TABLE "HBN_FORECAST" 
(	
   	"ID" NUMBER(9,0) NOT NULL, 
	"NAME" VARCHAR2(100 BYTE) NOT NULL, 
	"DESCRIPTION" VARCHAR2(100 BYTE), 
	"VALUE" NUMBER(5,2) NOT NULL, 
	"START_DATE" DATE, 
    "PRODUCT" NUMBER(9, 0), 
	
	CONSTRAINT "PK_HBN_FORECAST" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_FORECAST_PRODUCT" FOREIGN KEY ("PRODUCT") REFERENCES "HBN_PRODUCT"("ID")
);
   
